### ISSUE TITLE
[BUG] North Macedonia returned as Eritrea

### ISSUE THREAD

**Issue by quotentiroler** [coordinates2country/coordinates2country#14]
It seems like the country North Macedonia is not being returned correctly.

**Comment by nicolas-raoul** [comment]
Thanks a lot for reporting this!

Indeed, North Macedonia (https://www.wikidata.org/wiki/Q221) is not in the CSV: https://github.com/coordinates2country/coordinates2country/blob/main/data/countries.csv

Its gray shade should be changed in [countries.xcf](https://github.com/coordinates2country/coordinates2country/blob/main/data/countries.xcf) from 214 to something available.

Would you be able to try? :-)

**Comment by nicolas-raoul** [comment]
Fixed in 1.7, would you mind checking? :-)
