### ISSUE TITLE
Namibia is shown as Thailand (lat,lon: -18.330, 23.666)

### ISSUE THREAD

**Issue by MoritzB1990** [coordinates2country/coordinates2country#16]
Namibia is shown as Thailand (lat,lon: -18.330, 23.666)

**Comment by nicolas-raoul** [comment]
Thanks for the feedback!
If you find any other issue please keep reporting, I hope I can fix it soon. 🙂

**Comment by nicolas-raoul** [comment]
Fixed in 1.7, would you mind checking? :-)

**Comment by MoritzB1990** [comment]
Works!
Thank you for the fast fix:)

Am Fr., 19. Juli 2024 um 07:48 Uhr schrieb Nicolas Raoul <
***@***.***>:

**Comment by nicolas-raoul** [comment]
Thanks for the confirmation!
Please note that the resolution is not super high it might have be detected as Botswana.
