### ISSUE TITLE
Can not use newest changes as there is no release for the countryCode on MavenCentral

### ISSUE THREAD

**Issue by ItzBubschki** [coordinates2country/coordinates2country#23]
I need the fixes of #20 to be available but there hasn't been a new release yet.
Any chance you can create a new release soon?

**Comment by nicolas-raoul** [comment]
Ah yes sorry I will release as soon as possible. Thank you for the reminder! :-)

**Comment by nicolas-raoul** [comment]
Released `1.9`, it should become available within a day or so. :-)

**Comment by nicolas-raoul** [comment]
Live now at https://mvnrepository.com/artifact/io.github.coordinates2country/coordinates2country/1.9 :-)
