### ISSUE TITLE
Belgian coordinates shown as Morocco

### ISSUE THREAD

**Issue by Berthje** [coordinates2country/coordinates2country#3]
When coordinates in Belgium are given, 50.860, 4.325 for instance, it returns Morocco as the country.

**Comment by nicolas-raoul** [comment]
Thanks for your feedback!
I will fix this as soon as possible.

**Comment by nicolas-raoul** [comment]
This is fixed now with version 1.3.
Please do not hesitate to report other issues. :-)

**Comment by nicolas-raoul** [comment]
Sorry I meant 1.4 :-)
