### ISSUE TITLE
No matching variant of io.github.coordinates2country:coordinates2country:1.4 was found.

### ISSUE THREAD

**Issue by Berthje** [coordinates2country/coordinates2country#4]
I changed the gradle build from 1.2 to 1.4 to fix the Belgium bug.

I get this error:

![image](https://github.com/coordinates2country/coordinates2country/assets/63054630/642a2f58-6a2b-4387-b5ca-d3ddb2c80491)

EDIT:

I see if it searches the gradle dependecies, the version 1.4 is still not available on the internet:
![image](https://github.com/coordinates2country/coordinates2country/assets/63054630/8d4fd1f3-b854-4ee3-a572-a00c48764954)

**Comment by nicolas-raoul** [comment]
could you try with 1.3?

**Comment by Berthje** [comment]
also not working, see my issue screenshot, 1.3 and 1.4 aren't available yet.

**Comment by Berthje** [comment]
> could you try with 1.3?
also not working, see my issue screenshot, 1.3 and 1.4 aren't available yet somehow.

**Comment by Berthje** [comment]
It is not working, can you look into it, if so, can I get a confirmation?
Thanks already!

**Comment by Berthje** [comment]
[image: image.png]

You see, he can't find it on the jar, on the web, or via the import, it isl
ike the version is not published?

**Comment by nicolas-raoul** [comment]
There might be some delays before servers are able to serve new versions.

I now see 1.4 at https://mvnrepository.com/artifact/io.github.coordinates2country/coordinates2country :

![Screenshot from 2023-12-12 16-40-50](https://github.com/coordinates2country/coordinates2country/assets/99590/10bc4001-3731-4721-83c8-2833da2d9aff)

**Comment by Berthje** [comment]
Yes i know, i tried now still the same, even refreshed the gradle
dependencies cache etc.

Still not working... it gives this error maybe you as the dev of the
library can check it?

Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve
io.github.coordinates2country:coordinates2country:1.4.
     Required by:
         project :
      > No matching variant of
io.github.coordinates2country:coordinates2country:1.4 was found. The
consumer was configured to find a library for use during compile-time,
compatible with Java 17, preferably in the form of class files, preferably
optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability
io.github.coordinates2country:coordinates2country:1.4 declares a library
for use during compile-time, packaged as a jar, and its dependencies
declared externally:
              - Incompatible because this component declares a component,
compatible with Java 21 and the consumer needed a component, compatible
with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment
(preferred optimized for standard JVMs)
          - Variant 'javadocElements' capability
io.github.coordinates2country:coordinates2country:1.4 declares a component
for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation
and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment
(preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version
(required compatibility with Java 17)
                  - Doesn't say anything about its elements (required them
preferably in the form of class files)
          - Variant 'runtimeElements' capability
io.github.coordinates2country:coordinates2country:1.4 declares a library
for use during runtime, packaged as a jar, and its dependencies declared
externally:
              - Incompatible because this component declares a component,
compatible with Java 21 and the consumer needed a component, compatible
with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment
(preferred optimized for standard JVMs)
          - Variant 'sourcesElements' capability
io.github.coordinates2country:coordinates2country:1.4 declares a component
for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation
and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment
(preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version
(required compatibility with Java 17)
                  - Doesn't say anything about its elements (required them
preferably in the form of class files)

**Comment by Berthje** [comment]
I might have found the error in your code:

[image: image.png]
you see 1.2 has gradle version and buildId
but your 1.4 only has gradle version and not the buildId, perhaps that is
the problem?
[image: image.png]

**Comment by Berthje** [comment]
I found it, the version of my project was in Java 17 and when I changed it
to Java 21, it worked, is it possible to make the library work aswell on
java 17?

thanks in advance

**Comment by nicolas-raoul** [comment]
I am glad that you managed to run it with Java 21! 🙂
Would you mind creating a new issue about Java 17 compatibility?
Thanks!

**Comment by Berthje** [comment]
Thanks for answering! I made an issue.

**Comment by nicolas-raoul** [comment]
Le's continue the conversation on the relevant issue. 🙂
