### ISSUE TITLE
Java 17 unsupported, 1.3 and 1.4 only work with Java 21

### ISSUE THREAD

**Issue by Berthje** [coordinates2country/coordinates2country#5]
```
Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve io.github.coordinates2country:coordinates2country:1.4.
     Required by:
         project :
      > No matching variant of io.github.coordinates2country:coordinates2country:1.4 was found. The consumer was configured to find a library for use during compile-time, compatible with Java 17, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability io.github.coordinates2country:coordinates2country:1.4 declares a library for use during compile-time, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 21 and the consumer needed a component, compatible with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'javadocElements' capability io.github.coordinates2country:coordinates2country:1.4 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 17)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability io.github.coordinates2country:coordinates2country:1.4 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 21 and the consumer needed a component, compatible with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'sourcesElements' capability io.github.coordinates2country:coordinates2country:1.4 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 17)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
```

Most important line here is:

`Incompatible because this component declares a component, compatible with Java 21 and the consumer needed a component, compatible with Java 17`

**Comment by Berthje** [comment]
Is it possible to let this library run on the Java 17 and not only Java 21?

**Comment by nicolas-raoul** [comment]
Any chance you can switch your project to Java 21?

If not, could you try downgrading Gradle's version until it works for you?

**Comment by nicolas-raoul** [comment]
Also, please paste here the full error (as text, not only screenshot) when you try to use 1.4 with Java 17. Thanks!

**Comment by Berthje** [comment]
> Any chance you can switch your project to Java 21?
> 
> If not, could you try downgrading Gradle's version until it works for you?

No, it is not possible to switch project to Java 21, that is why I am hoping the library would support Java 17 etc.

Gradle version, tried 8.0, 8.1, 8.2, 8.3, 8.4 and 8.5, not working.

**Comment by Berthje** [comment]
> Also, please paste here the full error (as text, not only screenshot) when you try to use 1.4 with Java 17. Thanks!

Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve io.github.coordinates2country:coordinates2country:1.4.
     Required by:
         project :
      > No matching variant of io.github.coordinates2country:coordinates2country:1.4 was found. The consumer was configured to find a library for use during compile-time, compatible with Java 17, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability io.github.coordinates2country:coordinates2country:1.4 declares a library for use during compile-time, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 21 and the consumer needed a component, compatible with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'javadocElements' capability io.github.coordinates2country:coordinates2country:1.4 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 17)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability io.github.coordinates2country:coordinates2country:1.4 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 21 and the consumer needed a component, compatible with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'sourcesElements' capability io.github.coordinates2country:coordinates2country:1.4 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 17)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)

**Comment by nicolas-raoul** [comment]
Could you please try with **1.5**?

I am able to build the sample program that calls it, with Java 17 :-)
```
coordinates2country-sample nicolasraoul$ JAVA_HOME=`/usr/libexec/java_home -v 17.0.9` ./gradlew build

BUILD SUCCESSFUL in 592ms
```

**Comment by Berthje** [comment]
I will try! Thanks.

**Comment by Berthje** [comment]
It works now with Java 17, thanks for the update!

**Comment by nicolas-raoul** [comment]
Glad to hear that, you're welcome!
Please let me know if there is anything else to improve. :-)
